-- MySQL Script generated by MySQL Workbench
-- Tue Mar 26 12:58:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dormtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dormtest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dormtest` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_vietnamese_ci ;
USE `dormtest` ;

-- -----------------------------------------------------
-- Table `dormtest`.`student_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`student_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `department` VARCHAR(250) NOT NULL,
  `course` VARCHAR(250) NOT NULL,
  `gender` VARCHAR(20) NOT NULL,
  `contact` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

--
-- Dumping data for table `student_list`
--

INSERT INTO `student_list` (`id`, `code`, `name` , `department`, `course`, `gender`, `contact`, `email`, `address`) VALUES
(3, '2001180172', 'Phan Thanh Trong', 'Cong Nghe Thong Tin', 'Cong Nghe Phan Mem', 'Nam', '123456789', 'trong@gmail.com', '55B Tran Phu');

-- -----------------------------------------------------
-- Table `dormtest`.`account_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`account_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_list_id` INT NOT NULL,
  `username` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `avatar` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_list_student_list1_idx` (`student_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_list_student_list1`
    FOREIGN KEY (`student_list_id`)
    REFERENCES `dormtest`.`student_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

--
-- Dumping data for table `account_list`
--

INSERT INTO `account_list` (`id`, `student_list_id`, `username`, `password`, `avatar`) VALUES
(3, 3, 'trong', '123', 'ImageStudent');
-- -----------------------------------------------------
-- Table `dormtest`.`dorm_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`dorm_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

--
-- Dumping data for table `dorm_list`
--

INSERT INTO `dorm_list` (`id`, `name`) VALUES
(6, 'Ký túc nam 1'),
(7, 'Ký túc nữ 1');
-- -----------------------------------------------------
-- Table `dormtest`.`payment_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`payment_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `month_of` VARCHAR(50) NOT NULL,
  `amount` FLOAT(12,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `account_id` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id_fk_pl`
    FOREIGN KEY (`account_id`)
    REFERENCES `dormtest`.`account_list` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dormtest`.`room_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`room_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dorm_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `slots` INT NOT NULL DEFAULT '0',
  `price` FLOAT(12,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `dorm_id` (`dorm_id` ASC) VISIBLE,
  CONSTRAINT `drom_id_fk_rl`
    FOREIGN KEY (`dorm_id`)
    REFERENCES `dormtest`.`dorm_list` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `room_list` (`id`, `dorm_id`, `name`, `slots`, `price`) VALUES
(8, 6, 'A101', 4, 300000.00),
(9, 6, 'B102', 2, 1200000.00),
(10, 7, 'D102', 4, 600000.00),
(11, 7, 'C101', 2, 1200000.00);
-- -----------------------------------------------------
-- Table `dormtest`.`register_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`register_list` (
  `id` INT NOT NULL,
  `room_list_id` INT NOT NULL,
  `account_list_id` INT NOT NULL,
  `date` VARCHAR(50) NOT NULL,
  `is_registed` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registers_list_room_list1_idx` (`room_list_id` ASC) VISIBLE,
  INDEX `fk_registers_list_account_list1_idx` (`account_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_registers_list_room_list1`
    FOREIGN KEY (`room_list_id`)
    REFERENCES `dormtest`.`room_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registers_list_account_list1`
    FOREIGN KEY (`account_list_id`)
    REFERENCES `dormtest`.`account_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
