-- MySQL Script generated by MySQL Workbench
-- Sat Mar 16 21:28:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dormtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dormtest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dormtest` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_vietnamese_ci;
USE `dormtest` ;

-- -----------------------------------------------------
-- Table `dormtest`.`dorm_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`dorm_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dormtest`.`room_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`room_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dorm_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `slots` INT NOT NULL DEFAULT '0',
  `price` FLOAT(12,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `dorm_id` (`dorm_id` ASC) VISIBLE,
  CONSTRAINT `drom_id_fk_rl`
    FOREIGN KEY (`dorm_id`)
    REFERENCES `dormtest`.`dorm_list` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dormtest`.`student_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`student_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(250) NOT NULL,
  `middlename` VARCHAR(250) NULL DEFAULT NULL,
  `lastname` VARCHAR(250) NOT NULL,
  `department` VARCHAR(250) NOT NULL,
  `course` VARCHAR(250) NOT NULL,
  `gender` VARCHAR(20) NOT NULL,
  `contact` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dormtest`.`account_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`account_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NOT NULL,
  `student_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `username` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `avatar` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `room_id` (`room_id` ASC) VISIBLE,
  CONSTRAINT `room_id_fk_al`
    FOREIGN KEY (`room_id`)
    REFERENCES `dormtest`.`room_list` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `student_id_fk_al`
    FOREIGN KEY (`student_id`)
    REFERENCES `dormtest`.`student_list` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dormtest`.`payment_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`payment_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `month_of` VARCHAR(50) NOT NULL,
  `amount` FLOAT(12,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `account_id` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id_fk_pl`
    FOREIGN KEY (`account_id`)
    REFERENCES `dormtest`.`account_list` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dormtest`.`system_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`system_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meta_field` TEXT NOT NULL,
  `meta_value` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dormtest`.`usersAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`usersAdmin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(250) NOT NULL,
  `middlename` VARCHAR(250) NULL DEFAULT NULL,
  `lastname` VARCHAR(250) NOT NULL,
  `username` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `avatar` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dormtest`.`Rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`Rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dormtest`.`Violations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dormtest`.`Violations` (
  `details` TEXT NULL DEFAULT NULL,
  `account_list_id` INT NOT NULL,
  `Rules_id` INT NOT NULL,
  INDEX `fk_Violations_account_list1_idx` (`account_list_id` ASC) VISIBLE,
  INDEX `fk_Violations_Rules1_idx` (`Rules_id` ASC) VISIBLE,
  CONSTRAINT `fk_Violations_account_list1`
    FOREIGN KEY (`account_list_id`)
    REFERENCES `dormtest`.`account_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Violations_Rules1`
    FOREIGN KEY (`Rules_id`)
    REFERENCES `dormtest`.`Rules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
